name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0

dev_dependencies:
   build_runner: any
   build_web_compilers: any
   flutter_web_test: any
   test: ^1.0.0

flutter:
  uses-material-design: true
